def get_cookies():
    return ("MMMMM... peanut butter!",
        "MMMMM... chocolate chip!",
        "MMMMM... snickerdoodle!",
        "MMMMM... oatmeal raisin!",
        "MMMMM... sugar cookie!",
        "MMMMM... gingersnap!",
        "MMMMM... shortbread!",
        "MMMMM... whoopie pie!",
        "MMMMM... kiss cookie!",
        "MMMMM... thumbprint!",
        "MMMMM... pinwheel!",
        "MMMMM... macaroon!",
        "MMMMM... gingerbread!",
        "MMMMM... macaron!",
        "MMMMM... cream filled!",
        "MMMMM... macadamia nut!",
        "MMMMM... mint chocolate chip!",
        "MMMMM... spicy chocolate chip!",
        "It was a fortune cookie! Your fortune is <redacted>!",
        "Someone called this biscotti a cookie but it was delicious anyway.",
        "Wait that wasn't a cookie, how'd a scone get in here?",
        "You think throwing it at an enemy may have been more effective.",
        "Well, that's gone.",
        "You are filled with **DETERMINATION**",
        "You thought it was chocolate chip but it was oatmeal raisin. Your disappointment is showing.",
        "A practical joker replaced the sugar in the recipe with salt, your tongue now hates you.",
        "Cookies are not the only right in this world... some day... you will see...",
        "Engraved into the back of the cookie was the name 'SchalaKitty'. You fear for what might happen next.",
        "A blue monster stares at you angrily. You fear you may have upset them.",
        "You believe it was the wrong kind of cookie.",
        "Or at least you tried to... you do not believe it was edible.",
        "You vaguely remember seeing that same cookie on the floor earlier.",
        "It was in the shape of a cat!",
        "You monster.",
        "An elderly wizard scolds you mumbling something about points.",
        "That was no ordinary cookie, it was a SUPER cookie!",
        "You collapse to the ground and wake up later in your pajamas in some strange land called Magicant.",
        "This causes a strange eye-like creature to summon a mechanical dragon.",
        "You have a sudden desire to paint everything blue.",
        "A strange green dinosaur looks at you curiously.",
        "This :cookie: is not compatible with your operating system.",
        "Wait, how did a jelly filled donut get in here?",
        "MMMMM... cookie!",
        "You've completely forgotten all about what the Oracle said, you don't believe in that crap.",
        "It was in the shape of a tree!",
        "It was in the shape of a person!",
        "It was in the shape of a car!",
        "It was in the shape of a Super Famicom :tm: cartridge!",
        "You forgot what you were doing.",
        "Something called a 'grue' is trying... has succeeded in eating you.",
        "[object Object]",
        "T̸̛̞̩͎͚͙͛̈́̓̈̍̎̏͌͘͝͠h̴͇̯̰̘̝͙̽̊͋̀͛̈͋̉͆̎͛̀͘͘͠a̶̛̦̫̮̦͎̲̻̅̓̂͂̇̓̋̒̀̿̂̄̃͠ẗ̴̛͍̳͉̪̬̝̻͙͍̀̀̇̀̔̐̍̀ ̶̞̥͖̰̥͇̎͊̏̈̓̎͝c̴̛̼̹̺̞̟͕̬̲̲̊͐̔̅͌̇̿̚͜o̵̱̬̐͐̒̓̔̋̃͠ö̵̢͚̫̠́́͂̆͂̓̌͂̓͝͝ķ̵̳͖̯͇̻͖͚͍̹̟͓͂̈́̐̅̀͝͝í̸̧̢̜̟̖̫̹̝̗̫͎̥͉̝̾̆̊́̄̉̂͌͆̉͜e̷̛̞͔̘̪̣͎̥̲̰̗̿̂̿͒̎̃͝ͅ ̸̧͚̳͎͖̜͑̅̈͑͗̃o̵̘͓͎̖͈̝͓̰̲̦͚͎̒̔̐̀͜ͅñ̴̨̡̼͉͓̺̫̲̻͖̒̉͌̌̓̍͋͘͝c̶̺̼̫̼̖̤͋͒̆̾ͅe̴̡͓͉̼̤͖̊̾̂̏̍̚̕͘ ̵̢̛̳͕̘͓̥̆̍̈́̃̍͋̒̆̌͗̇́̌̽b̶͚̙̘̜̞̤͖̙̺̳̉͐̂͛̆̽̕͝ę̸̛̭͙͙̪̼͛͘l̸̨̧̹̠͎̺̱̭̰͈̰̗͈̗̝̃̽̃̀͆̈̒͋͒̌̆̈́͒͐o̷͇̝̥̞̻͚̤̙̲̳̓͂̾̽̕͘̚͜͜n̶̞̦̝̠̈́̃́̌̍̐ͅͅġ̷̡̧͔͕̰̱̥̳́̈́̓̆̀̈́͗̈́̈́̆͘͜͝e̵̡̡̡͙̼̫̖̪̖͒̕d̶̝̘̗͔̯̘̰̮̟͖̮͆̋̅̄́̀̆̑̑̀̅̍͋ͅ ̵̢̯̳͋̑̾̾̋̉̔̓̑̚͝t̵̢̟̱̰̥̲̱̃̀̽̿̽̋͜͝o̶̧̧̰͇̖̳͇͔̖̪͐͂́͘͝ ̸̰̏͑̀͌͘Z̶̢͎͚̳̱͉͍̫̭̰̰͔̥͕͆͋͜Ȃ̴̲̗̤̞͕̌̀̎̓̓̆͑̐̊͜ͅĹ̶̛̘̗̰̥͎͚̫̱͎̦̻̳̪͑̍̀̊̓̀̇͒͘̚̕ͅG̷͈̙̭͖̘͌̌̈́̓̈Ő̴̩͚̀̊̈̎̊̔͋̓͆͊͝.̸̜͉̤̠͌̆̓",
        "<Insert cookie reaction text here>",
        "It's in the shape of a hand and filled with... greek salad?",
        "MMMMM... (Insert Company Name Here)'s famous (Insert Product Name Here)!",
        "That wasn't an ordinary cookie, it contained a Pomegranate of Power!",
        "It was cursed. You lose 15 points in each of your stats.",
        "You fall into a deep slumber and all of Zeromus's alternate sprites are revealed to you. Alas, you forget all about it once you wake up.",
        "Or at least you tried to, a small green creature steals it from you using magical powers.",
        "It was in the shape of a metroid!",
        "It was in the shape of a dodecahedron!",
        "It was in the shape of a Holiday Tree :tm:",
        "In some places, this is called a biscuit!",
        "You taste a lot of saffron. How much did this cookie cost to make!?",
        "That wasn't a cookie at all, how did a crab cake get in here?",
        "MMMMM... pumpkin spiced!",
        "<your message here>",
        "MMMMM... A delicious marble cookie baked by SchalaKitty hirself!",
        "Did you know that the critically acclaimed MMORPG Final Fantasy XIV has a free trial, and includes the entirety of A Realm Reborn AND the award-winning Heavensward and Stormblood expansions up to level 70 with no restrictions on playtime? Sign up, and enjoy Eorzea today! https://secure.square-enix.com/account/app/svc/ffxivregister?lng=en-us",
        "MMMMM... Legally distinct cream filled cookie!",
        "MMMMM... Coffee Crisp!",
        "Or at least you tried to, it turned into mist.",
        "Or at least you tried to, you forgot to accept all cookies!",
        "MMMMM... wait, is that potato?",
        "Why do the cookies keep decreasing?",
        "It was in the shape of a penguin!",
        "You have seen that THAT is the way the cookie crumbles. Intersting!"
        )

def get_hook():
    return (
        "I've lost my marbles",
        "To a ten year-old I'm huge.",
        "Oh, I hate being disappointed, Smee. And I hate living in this flawed body. And I hate living in Neverland. And I hate... I hate... I *hate* Peter Pan!",
        "If you can't imagine yourself being Peter Pan, you won't *be* Peter Pan, so eat up.",
        "Hook routes are the worst.",
        "I've just had an apostrophe.",
        "To die would be a grand adventure!",
        "In three days, we're gonna have a war! A battle between good and evil to the death!",
        "It doesn't matter what I say, so long as I sing with inflection",
        "I ain't tellin' you no lie. The Hook brings you back, on that you can rely",
        "I wanna burn all of your cities to the ground"
    )

def get_greetings():
    return (
        'Tip: Baron Inn is the best place for up to date news and extras.',
        'Can I interest you in a hook route?',
        'Why do the seeds keep increasing?',
        'Only the best players fade Antlion.',
        'I\'m here to repair the refund machine.',
        'Would you like a good plate of brisky?',
        'Eblan Castle: come for the treasure, stay for the monsters!',
        'I\'m the error inside.',
        'Have you heard the news that the world isn\'t ending?',
        'But it was a beginning.',
        'I was twelve, and the twins thirteen, the night the stars disappeared from the sky.',
        'I\'ll make my report as if I told a story, for I was taught as a child on my homeworld that Truth is a matter of the imagination.',
        'It seems to be working.',
        'Did you know that https://wiki.ff4fe.com/ has lots of great information?',
        'I\'ve been here the whole time!',
        'The Moon blew up without warning and for no apparent reason.',
        'I will proclaim the to the world the deeds of Gilgamesh.',
        'Stay awhile, and listen',
        'Consider the magical sword',
        'I come in value packs of ten (in five varieties)'
    )

def get_post_roll_snark():
    return (
        'I recalled a seed I had forgotten.  Hopefully there wasn\'t a reason to forget it.',
        'Please remember to keep your arms, legs, and spoon inside the seed at all times.',
        'Well that seed\'s gone. . .',
        'Was it Random? I will show you how!',
        'Seed has 34.3 percent chance of betrayal by dragoon.',
        'Set your watches to Wyvern Daylight Time.',
        'I hope you start with Kain!',
        'Bosa?',
        'Phew, for a minute there, I lost myself.',
        'Gas \'em up with the greens and let him go',
        'It was offered to me by name',
        'Don\'t blame me. Blame yourself, or God.',
        'There\'s something lurking in the water. You better swim a little faster now',
        'It was a dumb thing to do but it wasn\'t that dumb',
        'You were so right when you said that I\'ve been drinking',
        'so much depends upon a red lunarian',
        'I don\'t know what I expected.',
        'How long will it last? How long \'til you learn?',
        "And I'll jump, jump, jump until I reach the sun",
        "You can't escape your fate",
        "What's done cannot be undone.",
        "I had a plan that was built on thinking too long"
    )

def get_pre_roll_snark():
    return (
        'Workin\' on it boss.',
        'As you wish!',
        'Would you like cheese with that?',
        'Guac is extra.',
        'It\'s a tiny town after all.',
        'I\'m not in danger. I\'m the danger.',
        'Really hopin\' for a nice bowl of soup.',
        'If you came to kill Chaos, this is the wrong game.',
        'Ice rods are easy to find!',
        'I love plums for breakfast.',
        'Men think they are better than grass',
        'Ahh! Z, Mandy, us!',
        'Time to turn back and descend the stair',
        'Do you have any ore? I have sheep!',
        'Maybe everything that falls down eventually rises.',
        'What we lose in the flame, we gain in the flood.',
        'I agree, you were right to say we\'re doomed.',
        'There is an art to the building up of suspense.',
        'Fair is foul and foul is fair. Hover through the fog and filthy air.',
        'Suppose time is a circle, bending back on itself.',
        'The worm drives helically through the wood and does not know that the dust left in the bore once made the table integral and good; and suddenly the crystal hits the floor.',
        'This is the most important moment in our lives, and I want to pay attention, note every detail.',
        "Didn't know I had this many scars; I thought I'd won all my different battles.",
        'Nothing will come of nothing.',
        'Something wicked this way comes.',
        'Fire burn, and cauldron bubble!'
    )